### ISSUE TITLE
text2phonemesequence causes cudaoutofmemory error

### ISSUE THREAD

**Issue by ghost** [VinAIResearch/XPhoneBERT#10]
while converting a dataset text file to a phoneme file, VRAM (24GB) goes out of usage. Any workaround for that? Running on cpu doesn't work either

**Comment by thelinhbkhn2014** [comment]
This is an example in our text2phonemesequence repo. You could reduce the batch_size to fit with your memory 
from text2phonemesequence import Text2PhonemeSequence

model = Text2PhonemeSequence(pretrained_g2p_model='charsiu/g2p_multilingual_byT5_small_100', language='eng-us', is_cuda=False)

model.infer_dataset(input_file="/absolute/path/to/input/file", output_file="/absolute/path/to/output/file", batch_size=64) # batch_size is the number of words fed into the CharsiuG2P toolkit per times. 

model.infer_sentence("The overwhelming majority of people in this country know how to sift the wheat from the chaff in what they hear and what they read .")

**Comment by clcarwin** [comment]
In preprocess.py, modify this line ```parser.add_argument("--batch_size", default=64, type=int)``` will fix cuda OOM. If not set the type to int, it will pass a string to Text2PhonemeSequence's batch_size.
