### ISSUE TITLE
Can you share any audio samples?

### ISSUE THREAD

**Issue by jun-danieloh** [VinAIResearch/XPhoneBERT#16]
If you can share samples, it would be very helpful!

**Comment by thelinhbkhn2014** [comment]
you can check it [here](https://drive.google.com/file/d/1VTUUd-IdxL2n_OX-JEmPUzxEyCqBo9k6/view?usp=sharing). I'm sorry about the late response. It's quite to be aware of the difference between 2 versions with the full dataset. But with only 5% data, the difference is quite clear, especially for a low-resource language like Vietnamese.
