### ISSUE TITLE
Finetune this model on a new language

### ISSUE THREAD

**Issue by gongchenghhu** [VinAIResearch/XPhoneBERT#17]
Hello, thank you for providing the multi-language model. I am interested in fine-tuning the model on a new language based on your framework. What steps should I take?

**Comment by thelinhbkhn2014** [comment]
You should follow my [Readme](https://github.com/VinAIResearch/XPhoneBERT/tree/main/VITS_with_XPhoneBERT#readme) but pay attention to adjusting language for the Text2phonemesequence tool in the preprocess.
