### ISSUE TITLE
Chinese data about tones

### ISSUE THREAD

**Issue by russell-shu** [VinAIResearch/XPhoneBERT#18]
hi,
have you taken chinese pinyin tones  into consider when training the model .
for example aishell3, ['chi2','qi3','hong2','ying1','qiang1'], were you process the data only in the way ['chi','qi','hong','ying','qiang']?

thanks in advance.

**Comment by thelinhbkhn2014** [comment]
We just used the [CharsiuG2P](https://github.com/lingjzhu/CharsiuG2P) to convert text to phonemes. The authors are Chinese, so I believe they were likely to care about it. Please check it at their repo.

**Comment by russell-shu** [comment]
您的来信已经收到啦，祝生活愉快~
