### ISSUE TITLE
About Bert

### ISSUE THREAD

**Issue by YuruW** [VinAIResearch/XPhoneBERT#2]
If I wanna train a phoneBert for prosody which can support both Chinese pinyin phoneme and English phoneme(phonetic symbol), what I should do?

**Comment by thelinhbkhn2014** [comment]
You need to follow some steps:
1. Prepare raw text for English and Chinese ar the sentence level. 
2. Using our text2phonemesequence library to convert raw text into phoneme sequences. Note that the raw text should be performed word segmentation and text normalization before using text2phonemesequence.
3. Finally, using fairseq or hugging face to train a phoneBERT model :D
