### ISSUE TITLE
Checkpoint request

### ISSUE THREAD

**Issue by ndhuynh02** [VinAIResearch/XPhoneBERT#22]
I am wanting to try out XPhoneBERT for my school project, but the main page [README.md](https://github.com/VinAIResearch/XPhoneBERT/blob/main/README.md) file doesn't clearly show how to generate audio from input text.
I have try it out though, and I find that the model I am inferring through is RoBERTa, not XPhoneBERT.
After that, I try looking for the infer code [inference.py](https://github.com/VinAIResearch/XPhoneBERT/blob/main/VITS_with_XPhoneBERT/inference.py). Fortunately, it it is in the [VITS_with_XPhoneBERT](https://github.com/VinAIResearch/XPhoneBERT/tree/main/VITS_with_XPhoneBERT) folder. In this code file, the model state reads from a checkpoint .pth file for inference. 
Therefore, I want to ask for this checkpoint so that I can use it for my school project.
Thank you.

**Comment by thelinhbkhn2014** [comment]
Thanks for your consideration, but sorry, following our company rules, I cannot release our TTS model
