### ISSUE TITLE
the problem of inference

### ISSUE THREAD

**Issue by AIM-yang** [VinAIResearch/XPhoneBERT#23]
Why are the synthesized audio outputs always 0 seconds or 1 second with no sound, and why is the synthesized mel spectrogram not showing up in TensorBoard?
![image](https://github.com/user-attachments/assets/eaec8a55-83df-4aa8-9cd9-cad4c0296b5c)

**Comment by wownaoh9** [comment]
Hello, I’ve encountered the same problem as you. Could you please tell me how you solved it? Thank you very much for your answer!
