### ISSUE TITLE
any audio samples?

### ISSUE THREAD

**Issue by innnky** [VinAIResearch/XPhoneBERT#3]

**Comment by thelinhbkhn2014** [comment]
Ok, we will update audio samples asap. Thanks for your interest!

**Comment by JettScythe** [comment]
Where can I find the audio samples?

**Comment by thelinhbkhn2014** [comment]
you can check it [here](https://drive.google.com/file/d/1VTUUd-IdxL2n_OX-JEmPUzxEyCqBo9k6/view?usp=sharing). I'm sorry about the late response. It's quite to be aware of the difference between 2 versions with the full dataset. But with only 5% data, the difference is quite clear, especially for a low-resource language like Vietnamese.
