### ISSUE TITLE
AttributeError: 'DistributedDataParallel' object has no attribute 'enc_p'

### ISSUE THREAD

**Issue by sonhm3029** [VinAIResearch/XPhoneBERT#7]
I 'm using torch==1.12.1 and met the error in train.p at this block code:

```
for epoch in range(epoch_str, hps.train.epochs + 1):
        if epoch < int(hps.train.epochs / 4):
            for child in net_g.enc_p.bert.children():
                for param in child.parameters():
                    param.requires_grad = False
        else:
            for child in net_g.enc_p.bert.children():
                for param in child.parameters():
                    param.requires_grad = True
```

 Please help me to fixed this and can you provide the version of python following with the update requirements.txt that should working. I currently using python 3.8.10
Many thanks!

**Comment by sourcesur** [comment]
@sonhm3029 

Hi
Just use net_g.module.enc_p.bert.children() instead of net_g.enc_p.bert.children()

**Comment by sonhm3029** [comment]
@sourcesur Thanks it working. Did you successfully training with this repo, please give me all the setup need ( python version, package require). Thanks again
