### ISSUE TITLE
[Bug] RuntimeError: stft requires the return_complex parameter be given for real inputs #2449

### ISSUE THREAD

**Issue by K2O7I** [VinAIResearch/XPhoneBERT#8]
Hi, I got this issue when I try to run this model in Google Colab. Is these any suggestion to fix this?

**Comment by thelinhbkhn2014** [comment]
Can you give me more detail about your issue?

**Comment by K2O7I** [comment]
![image](https://github.com/VinAIResearch/XPhoneBERT/assets/75080160/047d713f-c1ef-4cf4-a650-665d08deb334)
Hi, this is the issue I got when trying to train the model in Google Colab. 
The version of Python I use is 3.10 and the Torch version is 2.1. Hence, I wonder if this issue is caused by the Torch version.
Thank you for your response.

**Comment by thelinhbkhn2014** [comment]
Yes, It's exactly because of the torch version. You can check it in our requirement.txt [https://github.com/VinAIResearch/XPhoneBERT/blob/main/VITS_with_XPhoneBERT/requirements.txt](url) file .
