### ISSUE TITLE
Any comments on the size required for the dataset? (Also, can you share the pretrained models)

### ISSUE THREAD

**Issue by ghost** [VinAIResearch/XPhoneBERT#9]
Let's say I want to finetune/train base vits (ljspeech/libri tts) with XphoneBERT, presumably what shall be the size be the size of the dataset? Can a dataset with ~2000 clips (1 sec - 25 sec) work? Also, I would love to keep the sample rate ~44100. Any comments for the same?

Also, sharing a tts generated sample (result of finetuning tortoise-tts)

https://drive.google.com/file/d/1OfZnURiaAEW0O_B8RVozt1M4Uadl-rEV/view?usp=sharing

Any guide to make me achieve this level of tts quality would be appreciated.

Possible for you to share the pretrained VITS models (trained with XphoneBERT)?

**Comment by thelinhbkhn2014** [comment]
Currently, we have not yet supported training a multi-speaker TTS system. So It is not suitable to use the Libri TS dataset. It still works with a small dataset (~2h-->3h), however, to obtain high-quality audio, you should use the training data as much as possible.
We will publicize our pre-trained model when we can. Thanks for your interest!
